### ISSUE TITLE
may don't use collapse on connect with me due its only one item

### ISSUE THREAD

**Issue by schmelto** [UG-SEP/UG-SEP#1]
I would suggest to remove the collabs here due there is only one item "behind"

![image](https://user-images.githubusercontent.com/30869493/116914711-5dbb1b00-ac4b-11eb-8386-77da224e831b.png)

**Comment by ayushtamra** [comment]
Hey Ujjwal thats a really great profile,
For resolving this issue you can choose to take social badges from https://img.shields.io/

**Comment by UG-SEP** [comment]
@ayushtamra  thanks a lot for your suggestion

**Comment by schmelto** [comment]
> Hey Ujjwal thats a really great profile,
> For resolving this issue you can choose to take social badges from https://img.shields.io/

Bojaaa 🚀

**Comment by UG-SEP** [comment]
this issue had been solved  @schmelto
