### ISSUE TITLE
Some Improvement on Badges

### ISSUE THREAD

**Issue by Prathamesh-Shanbhag** [UG-SEP/UG-SEP#4]
### Things to improve:
- Consider removing the visitor's badge
- Remove Redundant Badges Like Repo Badge & Github Followers Badge

### Things I liked : 
- GitHub Actions!
- Simplicity of the Readme!
(Cannot Provide Screenshots connectivity issues, The badges aren't loading for me)

**Comment by UG-SEP** [comment]
@Prathamesh-Shanbhag  I will change it soon

**Comment by UG-SEP** [comment]
this issue have been solved  @Prathamesh-Shanbhag
