### ISSUE TITLE
typo in bot message

### ISSUE THREAD

**Issue by schmelto** [UG-SEP/UG-SEP#6]
`Thanks for opening a issue waiting for a contributor like you😁😁` ->
`Thanks for opening an issue waiting for a contributor like you😁😁`

change from `a` to `an`

![image](https://user-images.githubusercontent.com/30869493/116915352-33b62880-ac4c-11eb-9dc4-fdd7db20a7da.png)

**Comment by UG-SEP** [comment]
ok

**Comment by UG-SEP** [comment]
@schmelto I have changed it 
Thanks a lot
